# Generated by Django 3.2.4 on 2021-06-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210607_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'Новость'), ('article', 'Статья')], default='news', max_length=20),
            preserve_default=False,
        ),
    ]
